### PR TITLE
Save test report in a dedicated file - Feature/5

### PR DESCRIPTION
**Pull request by mageddo**
Features 
* [Based on Save test report in a dedicated file](https://github.com/mageddo/mocha-sonar-generic-test-coverage/pull/5)
* Demo Grunt project report 
* Unit tests

### CODE REVIEW

**Comment by mageddo** [comment]
Hey guys, this is my release candidate with your changes and my changes for standardization, to keep compatibility with your version I kept two options:

* Set report file by env
* New option to use fullpath file

I will wait for one week before merge it, if you guys have any suggestions please let me know.

Many Thanks @guilhem88 @topaxi

**Review by guilhem-lk — CHANGES_REQUESTED** [review]
Great! This is working fine on my project. If you prefer to use outputFile variable instead of an env var, you can delete mocha_sonar_generic_test_coverage_outputfile.

**Comment by mageddo** [comment]
Ok, Let's wait for @topaxi, then I will merge and release `0.0.2` NPM version

**Comment by topaxi** [comment]
I won't be able to test this, as I'm in the middle of a sonar upgrade and fully booked the rest of the week :)

**Comment by mageddo** [comment]
Ok @topaxi, let's generate a release of this, then if you a interested to test it let we know.

Thank you guys

**Comment by mageddo** [comment]
`0.0.2` (with env support) and `0.0.3` removing env support [was released](https://www.npmjs.com/package/mocha-sonar-generic-test-coverage).

Thank you for the new features, and you are welcome to contribute with more.

**Pull request merged**
