### PR TITLE
Updated to conform to SonarQube >6.2

### PR DESCRIPTION
**Pull request by timarandras**
https://docs.sonarqube.org/display/PLUG/Generic+Test+Coverage

### CODE REVIEW

**Comment by mageddo** [comment]
Can you confirm if is that compatible with old versions?

**Comment by mageddo** [comment]
I need to take a look at the documentation, but I think that old versions of Sonar will lost the compatibility. We need to create a option to turn on old sonarqube support if needle

**Comment by timarandras** [comment]
I am afraid that it isn't backwards compatible. Maybe the easiest solution would be to move this to a new branch called e.g. sonar_after_62. Or add a reporter option to choose the version.

**Comment by mageddo** [comment]
Okay, the tests are failing, I will make the tests pass and add a parameter to specify the sonar compability version

**Pull request merged**
